# Generated by Django 5.0.2 on 2024-02-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('features', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=13)),
            ],
        ),
    ]
