# Generated by Django 5.0.2 on 2024-02-26 09:18

import django.db.models.deletion
import server.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.FileField(blank=True, null=True, upload_to=server.models.upload_to)),
                ('description', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('features', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=25)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
