# Generated by Django 4.1.3 on 2024-02-15 05:23

from django.db import migrations, models
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostpet',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=server.models.upload_to),
        ),
    ]
