# Generated by Django 4.0.4 on 2024-02-16 07:08

from django.db import migrations, models
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_lostpet_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostpet',
            name='image_url',
            field=models.FileField(blank=True, null=True, upload_to=server.models.upload_to),
        ),
    ]
