# Generated by Django 4.0.4 on 2024-02-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_lostpet_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostpet',
            name='type',
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='number',
            field=models.CharField(max_length=25),
        ),
    ]
