# Generated by Django 5.0.2 on 2024-02-19 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_remove_lostpet_type_alter_lostpet_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LostPet',
            new_name='Pet',
        ),
    ]
