# Generated by Django 5.0.2 on 2024-02-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_pet_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publication_date', models.DateField()),
            ],
        ),
    ]
