# Generated by Django 4.0.4 on 2024-02-22 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
